//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yakutia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yakutia.Properties.QA", typeof(QA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Особенностью корпоративных юридических лиц является то, что после их создания
        ///учредители приобретают права членства и становятся их участниками.
        ///Понятие «учредитель» используется в корпоративных некоммерческих организациях
        ///только в отношении лиц, принявших решение о создании такой некоммерческой
        ///организации, и сведения о которых включены в единый государственный реестр
        ///юридических лиц (далее – ЕГРЮЛ) при создании организации.
        ///По общему правилу, в соответствии с пунктом 3 статьи 15 Федерального закона  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HowChangeCompositionFoundersPPublicOrganizationOrOtherCorporateNonProfitOrganization {
            get {
                return ResourceManager.GetString("HowChangeCompositionFoundersPPublicOrganizationOrOtherCorporateNonProfitOrganizat" +
                        "ion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В соответствии с пунктом 3 статьи 55 Гражданского кодекса Российской
        ///Федерации представительства и филиалы юридического лица должны быть указаны в
        ///едином государственном реестре юридических лиц.
        ///В случае создания филиала или открытия представительства некоммерческой
        ///организации в орган, принявший решение о государственной регистрации
        ///
        ///некоммерческой организации (Минюст России или его территориальный орган),
        ///представляются:
        ///заявление по форме № Р14001, утвержденной приказом ФНС России
        ///от 25.01.2012  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HowReportEstablishmentBranchOrRepresentativeOfficeNonProfitOrganization {
            get {
                return ResourceManager.GetString("HowReportEstablishmentBranchOrRepresentativeOfficeNonProfitOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Согласно пунктам 13 – 15 Административного регламента предоставления
        ///Министерством юстиции Российской Федерации государственной услуги по принятию
        ///решения о государственной регистрации некоммерческих организаций, утвержденного
        ///приказом Минюста России от 30 декабря 2011 г. № 455, консультации по вопросам
        ///государственной регистрации некоммерческих организаций предоставляются
        ///государственными служащими Минюста России и его территориальных органов при
        ///личном обращении, посредством интернет-сайта, телефонн [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HowToGetAdviceOnStateRegistrationOfNonProfitOrganizations {
            get {
                return ResourceManager.GetString("HowToGetAdviceOnStateRegistrationOfNonProfitOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С 2016 года изменилась процедура оформления изменения места нахождения
        ///юридического лица (адреса юридического лица, влекущего изменение места нахождения
        ///юридического лица). Исходя из положений пункта 6 статьи 17 и статьи 18 Федерального
        ///закона от 08.08.2001 № 129-ФЗ «О государственной регистрации юридических лиц и
        ///индивидуальных предпринимателей» (далее – Закон № 129-ФЗ) можно выделить два этапа
        ///оформления указанных изменений:
        ///1-й этап – в течение трех рабочих дней после принятия решения об изменении  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планы проверок некоммерческих организаций размещены на официальных сайтах
        ///Минюста России и его территориальных органов в информационно-
        ///телекоммуникационной сети «Интернет» www.minjust.ru (раздел «Деятельность в сфере
        ///некоммерческих организаций», подраздел «Контроль деятельности и отчетность
        ///некоммерческих организаций»).
        ///Информация о проверках некоммерческих организаций размещена в федеральной
        ///государственной информационной системе «Единый реестр проверок»
        ///(https://proverki.gov.ru), а также на официа [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Согласно статьям 11.1 и 11.2 Федерального закона от 27 июля 2010 г. № 210-ФЗ «Об
        ///организации предоставления государственных и муниципальных услуг», пункту 114
        ///Административного регламента предоставления Министерством юстиции Российской
        ///Федерации государственной услуги по принятию решения о государственной регистрации
        ///некоммерческих организаций, утвержденного приказом Минюста России от 30 декабря
        ///2011 г. № 455, заявитель имеет право на обжалование действий и (или) бездействия
        ///органа, предоставляющего г [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В связи с вступлением в силу Федерального закона от 21 июля 2014 г. № 236-ФЗ «О
        ///внесении изменений в отдельные законодательные акты Российской Федерации по
        ///вопросам символики некоммерческих организаций» с 2 августа 2014 г. государственная
        ///регистрация символики некоммерческих организаций не осуществляется.
        ///Описание используемой некоммерческой организацией символики должно быть
        ///включено в ее устав.
        ///В случае необходимости правовой защиты объекты интеллектуальной
        ///собственности, используемые в символике н [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Согласно статье 3 Федерального закона от 19 мая 1995 г. № 82-ФЗ «Об
        ///общественных объединениях» (далее – Закон № 82-ФЗ) создаваемые гражданами
        ///общественные объединения могут регистрироваться в порядке, предусмотренном
        ///законом, и приобретать права юридического лица либо функционировать без
        ///государственной регистрации и приобретения прав юридического лица.
        ///В соответствии со статьей 21 Закона № 82-ФЗ, пунктом 30.7 Положения о
        ///Министерстве юстиции Российской Федерации, утвержденного Указом Президента
        ///
        ///Ро [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В соответствии с пунктом 2.1 статьи 31.4 Закона № 7-ФЗ оценка качества оказания
        ///общественно полезных услуг (далее – ОПУ) социально ориентированной некоммерческой
        ///организацией (далее – СОНКО) осуществляется федеральными органами исполнительной
        ///власти и органами исполнительной власти субъектов Российской Федерации в
        ///соответствии с их компетенцией (далее – заинтересованные органы).
        ///Согласно пункту 5 Правил принятия решения о признании социально
        ///ориентированной некоммерческой организации исполнителем обще [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В соответствии со статьей 29 Федерального закона от 19 мая 1995 г. № 82-ФЗ «Об
        ///общественных объединениях» общественная организация или общественное движение
        ///обязаны ежегодно информировать орган, принявший решение об их государственной
        ///регистрации (Минюст России или его территориальный орган):
        ///о продолжении своей деятельности с указанием действительного места нахождения
        ///постоянно действующего руководящего органа, его наименования и данных о своих
        ///руководителях в объеме сведений, включаемых в единый гос [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В соответствии с пунктом 13 статьи 13.2 Федерального закона от 12 января 1996 г.
        ///№ 7-ФЗ «О некоммерческих организациях», приложением № 4 к приказу Минюста России
        ///от 28 июня 2012 г. № 122 выдача новой выписки предусмотрена только в случае
        ///изменения соответствующих сведений, содержащихся в уведомлении о создании на
        ///территории Российской Федерации филиала или представительства иностранной
        ///некоммерческой неправительственной организации.
        ///В иных случаях новая выписка не выдается..
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порядок предоставления информации центральным аппаратом Минюста России и
        ///его территориальными органами физическим и юридическим лицам о некоммерческих
        ///организациях, филиалах и представительствах иностранных некоммерческих
        ///неправительственных организаций (далее – зарегистрированные организации) установлен
        ///Административным регламентом предоставления Министерством юстиции Российской
        ///Федерации государственной услуги по предоставлению информации физическим и
        ///юридическим лицам о зарегистрированных организац [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участниками конкурса не могут быть (не допускаются до участия в конкурсе):
        ///потребительские кооперативы, к которым относятся в том числе жилищные,
        ///жилищно-строительные и гаражные кооперативы, садоводческие, огороднические и
        ///дачные потребительские кооперативы, общества взаимного страхования, кредитные
        ///кооперативы, фонды проката, сельскохозяйственные потребительские кооперативы;
        ///политические партии;
        ///саморегулируемые организации;
        ///объединения работодателей;
        ///объединения кооперативов;
        ///торгово-промышленные [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WhichOrganizationsCannot_participateInTheFundsCompetitionPresidentialGrants {
            get {
                return ResourceManager.GetString("WhichOrganizationsCannot participateInTheFundsCompetitionPresidentialGrants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В конкурсе могут участвовать некоммерческие неправительственные организации,
        ///соответствующие всем следующим требованиям:
        ///1) организация зарегистрирована не позднее чем за один год до дня окончания приема
        ///заявок на участие в конкурсе, а в случае если организация запрашивает грант в сумме до
        ///пятисот тысяч рублей, – не позднее чем за шесть месяцев до дня окончания приема заявок
        ///на участие в конкурсе;
        ///2) организация осуществляет в соответствии с уставом один или несколько видов
        ///деятельности, соответствую [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WhoCanTakePartInTheContestOfThePresidentialGrantsFund {
            get {
                return ResourceManager.GetString("WhoCanTakePartInTheContestOfThePresidentialGrantsFund", resourceCulture);
            }
        }
    }
}
